# Neden Numpy

In [2]:
a=[1,2,3,4]
b=[1,3,5,4]

In [4]:
import numpy as np

In [7]:
a=np.array([1,2,3,4])
b=np.array([1,3,5,4])

In [8]:
a*b

array([ 1,  6, 15, 16])

# NUMPY ARRAY'i Oluşturmak


In [9]:
import numpy as np

In [10]:
np.array([1,3,4,5])

array([1, 3, 4, 5])

In [11]:
a=np.array([1,3,4,5])

In [12]:
type(a)

numpy.ndarray

In [13]:
np.array([3.13,3,4,6,7])

array([3.13, 3.  , 4.  , 6.  , 7.  ])

In [16]:
b=np.array([3.13,3,4,6,7],dtype="int")

In [19]:
b

array([3, 3, 4, 6, 7])

## Sıfırdan array olusturma

In [22]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
np.ones((3,6),dtype="int")

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [25]:
np.full((3,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [27]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [28]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
np.random.normal(10,4,(3,4))

array([[ 3.91683487, 23.82616294, 11.99289521,  9.40259648],
       [13.01868025, 13.7660174 ,  7.938254  ,  4.64763829],
       [ 4.44625768,  9.27494579, 14.4829934 , 14.38308662]])

In [30]:
np.random.randint(0,10,(3,3))

array([[1, 9, 1],
       [8, 1, 1],
       [8, 1, 3]])