# **Özellikleri**

* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [3]:
import numpy as np

In [4]:
np.random.randint(10,size= 10)

array([3, 3, 5, 5, 4, 9, 1, 3, 7, 6])

In [5]:
a=np.random.randint(10,size= 10)

In [6]:
a.ndim

1

In [7]:
a.shape

(10,)

In [8]:
a.size

10

In [10]:
a.dtype

dtype('int32')

In [12]:
b=np.random.randint(10,size=(3,5))

In [13]:
b

array([[8, 4, 3, 4, 5],
       [2, 4, 9, 8, 0],
       [6, 5, 0, 8, 5]])

In [14]:
b.ndim

2

In [15]:
b.shape

(3, 5)

In [16]:
b.size

15

In [17]:
b.dtype

dtype('int32')

# Yeniden şekillendirme

In [18]:
import numpy as np

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a=np.arange(1,10)

In [22]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a.ndim

1

In [25]:
b=a.reshape((1,9))

In [26]:
b.ndim

2

# Array Birlestirme(concatenation)

In [27]:
import numpy as np

In [29]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [31]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [32]:
z=np.array([7,8,9])

In [33]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#iki boyut

In [38]:
a=np.array([[1,2,3],
           [4,5,6]])

In [39]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma(splitting) 

In [41]:
import numpy as np

In [42]:
x=np.array([21,57,35,96,93,46,66])

In [43]:
np.split(x,[3,5])

[array([21, 57, 35]), array([96, 93]), array([46, 66])]

In [44]:
a,b,c=np.split(x,[3,5])

In [45]:
a

array([21, 57, 35])

In [46]:
b

array([96, 93])

In [47]:
c

array([46, 66])

In [48]:
# iki boyutlu ayırma

In [50]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [52]:
ust,alt=np.vsplit(m,[2])

In [53]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [54]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [57]:
sag,sol=np.hsplit(m,[2])

In [58]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [59]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama(sorting)

In [60]:
import numpy as np

In [61]:
v=np.array([5,6,9,1,7,3,1])

In [62]:
v

array([5, 6, 9, 1, 7, 3, 1])

In [63]:
np.sort(v)

array([1, 1, 3, 5, 6, 7, 9])

In [64]:
v

array([5, 6, 9, 1, 7, 3, 1])

In [65]:
v.sort()

In [66]:
v

array([1, 1, 3, 5, 6, 7, 9])

In [67]:
# iki boyutlu aray sıralama

In [69]:
m=np.random.normal(20,5,(3,3))

In [70]:
m

array([[32.40476712, 26.33292209, 25.28234453],
       [26.15128068, 14.5989988 , 29.31875068],
       [21.77271452, 20.65613757, 30.27862069]])

In [71]:
np.sort(m,axis=1)

array([[25.28234453, 26.33292209, 32.40476712],
       [14.5989988 , 26.15128068, 29.31875068],
       [20.65613757, 21.77271452, 30.27862069]])

In [72]:
np.sort(m,axis=0)

array([[21.77271452, 14.5989988 , 25.28234453],
       [26.15128068, 20.65613757, 29.31875068],
       [32.40476712, 26.33292209, 30.27862069]])

# Index ile Elemanlara Erişmek

In [77]:
import numpy as np
a=np.random.randint(10,size=10)
a

array([0, 1, 3, 8, 2, 2, 8, 3, 3, 8])

In [78]:
a[0]

0

In [79]:
a[0]=32

In [80]:
a

array([32,  1,  3,  8,  2,  2,  8,  3,  3,  8])

In [82]:
m=np.random.randint(10,size=(3,5))
m

array([[3, 5, 2, 0, 5],
       [5, 3, 9, 7, 3],
       [5, 6, 1, 5, 9]])

In [83]:
m[0,0]

3

In [84]:
m[2,4]

9

In [86]:
m[0,0]=2.7
m

array([[2, 5, 2, 0, 5],
       [5, 3, 9, 7, 3],
       [5, 6, 1, 5, 9]])

# Slicing ile elemanlara erişmek 
# (array ile alt kümesine erişmek)

In [87]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [88]:
a[0:3]

array([20, 21, 22])

In [89]:
a[:3]

array([20, 21, 22])

In [90]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [91]:
a[1::3]

array([21, 24, 27])

In [92]:
# iki boyulu slice islemleri

In [95]:
m=np.random.randint(10,size=(5,5))
m

array([[3, 9, 2, 9, 5],
       [8, 5, 1, 5, 1],
       [5, 2, 0, 7, 7],
       [4, 6, 2, 3, 4],
       [1, 2, 6, 8, 5]])

In [96]:
m[:,0]

array([3, 8, 5, 4, 1])

In [97]:
m[:,3]

array([9, 5, 7, 3, 8])

In [98]:
m[2,:]

array([5, 2, 0, 7, 7])

In [99]:
m[0,:]

array([3, 9, 2, 9, 5])

In [100]:
m[1]

array([8, 5, 1, 5, 1])

In [101]:
m[0:2,0:3]

array([[3, 9, 2],
       [8, 5, 1]])

In [103]:
m[::,0:2]

array([[3, 9],
       [8, 5],
       [5, 2],
       [4, 6],
       [1, 2]])

In [108]:
m

array([[3, 9, 2, 9, 5],
       [8, 5, 1, 5, 1],
       [5, 2, 0, 7, 7],
       [4, 6, 2, 3, 4],
       [1, 2, 6, 8, 5]])

In [109]:
m[1:3,:2]

array([[8, 5],
       [5, 2]])

# Alt küme üzerinde işlem Yapmak

In [110]:
import numpy as np
a= np.random.randint(10,size=(5,5))
a

array([[6, 7, 9, 8, 2],
       [7, 5, 8, 7, 0],
       [6, 9, 8, 0, 3],
       [3, 5, 6, 8, 2],
       [2, 0, 4, 1, 8]])

In [111]:
alt_a=a[0:3,0:2]
alt_a

array([[6, 7],
       [7, 5],
       [6, 9]])

In [112]:
alt_a[0,0]=9999
alt_a[1,1]=8888
alt_a

array([[9999,    7],
       [   7, 8888],
       [   6,    9]])

In [113]:
a

array([[9999,    7,    9,    8,    2],
       [   7, 8888,    8,    7,    0],
       [   6,    9,    8,    0,    3],
       [   3,    5,    6,    8,    2],
       [   2,    0,    4,    1,    8]])

In [114]:
m= np.random.randint(10,size=(5,5))
m

array([[8, 7, 3, 3, 4],
       [3, 3, 1, 0, 5],
       [1, 2, 5, 5, 6],
       [6, 5, 6, 6, 3],
       [1, 9, 7, 7, 8]])

In [119]:
alt_b=m[0:3,0:2].copy()#bağımsızlığı sağlamış oluruz.
alt_b

array([[8, 7],
       [3, 3],
       [1, 2]])

In [116]:
alt_b[0,0]=999
alt_b[1,1]=888
alt_b

array([[999,   7],
       [  3, 888],
       [  1,   2]])

In [118]:
m

array([[8, 7, 3, 3, 4],
       [3, 3, 1, 0, 5],
       [1, 2, 5, 5, 6],
       [6, 5, 6, 6, 3],
       [1, 9, 7, 7, 8]])

# Fancy Index ile elemanlara Erişmek***

In [120]:
import numpy as np
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [122]:
[v[0],v[1],v[2]]

[0, 3, 6]

In [123]:
al_getir=[1,3,5]
al_getir

[1, 3, 5]

In [125]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [126]:
v[al_getir]

array([ 3,  9, 15])

In [127]:
# iki boyutta fancy

In [128]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [167]:
satir=np.array([0,1])
sutun=np.array([1,2])
m[satir]

array([[0, 1, 2],
       [3, 4, 5]])

In [178]:
m[1,sutun]

array([4, 5])

In [177]:
m[satir,sutun]

array([1, 5])

In [181]:
m[[0,2],[0,1]]
#burada[a,b],[d,c] -> a.satırda d. sutunu al,
#b.satırda c.sutunu al demek.

array([0, 7])

In [182]:
#Basit index ile fancy index

In [183]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [186]:
m[0,[1,2]]

array([1, 2])

In [185]:
#slice

In [187]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman işlemleri

In [189]:
import numpy as np
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [190]:
v>5

array([False, False, False, False, False])

In [191]:
v<3

array([ True,  True, False, False, False])

In [192]:
v[v<3]

array([1, 2])

In [193]:
v[v>3]

array([4, 5])

In [194]:
v[v>=3]

array([3, 4, 5])

In [196]:
v[v!=3]

array([1, 2, 4, 5])

In [197]:
v*2

array([ 2,  4,  6,  8, 10])

In [198]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [199]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

# Matematiksel İşlemler

In [200]:
import numpy as np
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [201]:
v-1

array([0, 1, 2, 3, 4])

In [203]:
# ufunc

In [206]:
np.subtract(v,1)#v-1 ile aynı is ufanc kavrami isler.

array([0, 1, 2, 3, 4])

In [209]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [211]:
v%2#np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [215]:
np.absolute(np.array([-5]))

array([5])

In [216]:
np.sin(360)

0.9589157234143065

In [217]:
v=np.array([1,2,3])
v

array([1, 2, 3])

In [219]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [220]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [222]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\yahya\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\yahya\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x

In [224]:
#cheatsheet

In [235]:
np.mean(m,axis=1)

array([1., 4., 7.])

In [227]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Numpy ile iki Bilinmeyenli deklem çözümü

In [245]:
import numpy as np

* 5*x_0+x_1=12
* x_0+3*x_1=10

In [277]:
a=np.array([[5,1],[1,3]])
b=np.array([[12],[10]])

In [278]:
a

array([[5, 1],
       [1, 3]])

In [279]:
b

array([[12],
       [10]])

In [280]:
x=np.linalg.solve(a,b)
x

array([[1.85714286],
       [2.71428571]])